import { demoNow } from "../../clock";
import type {
  Asset,
  Execution,
  Incident,
  InventoryItem,
  MaintenanceTool,
  Notification,
  OperationalFlow,
  Person,
  Protocol,
  ResourceReservation,
  Schedule,
  ServiceRequest,
  Skill,
  StoreAssignment,
  SupportCase,
  SupportIntervention,
} from "../../../ove/types";

const today = demoNow().format("YYYY-MM-DD");
const yesterday = demoNow().subtract(1, "day").format("YYYY-MM-DD");
const openingWindow = demoNow().add(1, "hour").startOf("hour");
const serviceWindow = demoNow().add(3, "hour").startOf("hour");

export const plants = [
  "Boutique Norte",
  "Boutique Centro",
  "Boutique Valle",
  "Boutique Oriente",
  "Boutique Poniente",
  "Boutique Aeropuerto",
];
export const branches = plants;
export const operators = ["Valeria Santos", "Sergio Luna", "Camila Torres"];
export const supervisors = ["Laura Mendoza", "Elena Ríos"];
export const categories = [
  "Apertura y presentación",
  "Recepción de mercancía",
  "Limpieza y orden",
  "Climatización",
  "Ventas e intenciones",
  "Medidas y servicio",
  "Soporte de activos",
];

export const seedAssets: Asset[] = [
  {
    id: "CLM-02",
    name: "Unidad de climatización sala de ventas",
    family: "Climatización",
    plant: "Boutique Norte",
    area: "Sala de ventas",
    criticality: "High",
    status: "Risk",
    availabilityStatus: "Available",
    operationalCondition: "Review",
    availability: 91.8,
    health: 68,
    runtimeHours: 9420,
    lastService: demoNow().subtract(61, "day").toISOString(),
  },
  {
    id: "POS-04",
    name: "Terminal de punto de venta 04",
    family: "Punto de venta",
    plant: "Boutique Centro",
    area: "Caja",
    criticality: "Critical",
    status: "Available",
    availabilityStatus: "Available",
    operationalCondition: "Operating",
    availability: 99.2,
    health: 94,
    runtimeHours: 6150,
    lastService: demoNow().subtract(14, "day").toISOString(),
  },
  {
    id: "NET-03",
    name: "Gateway de conectividad",
    family: "Red y conectividad",
    plant: "Boutique Valle",
    area: "Back office",
    criticality: "High",
    status: "Maintenance",
    availabilityStatus: "Assigned",
    operationalCondition: "Maintenance",
    estimatedReleaseAt: demoNow().add(3, "hour").toISOString(),
    availability: 95.1,
    health: 76,
    runtimeHours: 12100,
    lastService: demoNow().subtract(30, "day").toISOString(),
  },
  {
    id: "LGT-11",
    name: "Circuito de iluminación escaparate",
    family: "Iluminación",
    plant: "Boutique Oriente",
    area: "Escaparate",
    criticality: "Medium",
    status: "Maintenance",
    availabilityStatus: "Assigned",
    operationalCondition: "Maintenance",
    estimatedReleaseAt: demoNow().add(5, "hour").toISOString(),
    availability: 88.5,
    health: 72,
    runtimeHours: 5020,
    lastService: demoNow().subtract(90, "day").toISOString(),
  },
  {
    id: "PRN-06",
    name: "Impresora de tickets",
    family: "Punto de venta",
    plant: "Boutique Poniente",
    area: "Caja",
    criticality: "Medium",
    status: "Available",
    availabilityStatus: "Available",
    operationalCondition: "Operating",
    availability: 98.6,
    health: 91,
    runtimeHours: 4380,
    lastService: demoNow().subtract(9, "day").toISOString(),
  },
  {
    id: "SEC-08",
    name: "Cortina de acceso principal",
    family: "Acceso y seguridad",
    plant: "Boutique Aeropuerto",
    area: "Acceso principal",
    criticality: "High",
    status: "Available",
    availabilityStatus: "Available",
    operationalCondition: "Operating",
    availability: 99.4,
    health: 96,
    runtimeHours: 3120,
    lastService: demoNow().subtract(20, "day").toISOString(),
  },
];

export const seedSkills: Skill[] = [
  { id: "sk-store", name: "Operación de tienda", category: "Technical" },
  { id: "sk-support", name: "Diagnóstico remoto", category: "Technical" },
  { id: "sk-hvac", name: "Servicio de climatización", category: "Certification" },
  { id: "sk-safety", name: "Seguridad en tienda", category: "Safety" },
];

export const seedPeople: Person[] = [
  {
    id: "per-valeria",
    name: "Valeria Santos",
    role: "Technician",
    plant: "Boutique Norte",
    shift: "Morning",
    skillIds: ["sk-store", "sk-safety"],
    status: "Assigned",
  },
  {
    id: "per-diego",
    name: "Diego Castro",
    role: "Technician",
    plant: "Centro de soporte",
    shift: "Morning",
    skillIds: ["sk-support", "sk-safety"],
    status: "Available",
  },
  {
    id: "per-laura",
    name: "Laura Mendoza",
    role: "Supervisor",
    plant: "Gerencia de sucursales",
    shift: "Morning",
    skillIds: ["sk-store", "sk-support"],
    status: "Available",
  },
  {
    id: "per-sergio",
    name: "Sergio Luna",
    role: "Technician",
    plant: "Boutique Centro",
    shift: "Morning",
    skillIds: ["sk-store"],
    status: "Assigned",
  },
];

export const seedTools: MaintenanceTool[] = [
  {
    id: "tool-temp",
    name: "Termómetro ambiental",
    serial: "TMP-RETAIL-12",
    plant: "Boutique Norte",
    location: "Back office",
    status: "Available",
    calibrationValidUntil: demoNow().add(8, "month").format("YYYY-MM-DD"),
  },
];

export const seedInventory: InventoryItem[] = [];

const commonStoreEvidence = [
  { id: "gps", type: "GPS" as const, required: true, radius: 80, label: "Ubicación de tienda" },
  {
    id: "photo",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Evidencia del área",
    guidance: "Captura el área completa sin incluir clientes ni información personal.",
  },
  { id: "timestamp", type: "Timestamp" as const, required: true, label: "Fecha y hora" },
];

export const seedProtocols: Protocol[] = [
  {
    id: "retail-merchandise-receipt",
    name: "Recepción de mercancía en tienda",
    description:
      "Confirma entrega, cantidades, condición de paquetes, evidencia y conformidad de la persona que recibe.",
    category: "Recepción de mercancía",
    priority: "High",
    status: "Active",
    branches: plants,
    recurrence: "Once",
    schedule: [{ hour: "11:30", tolerance: 30 }],
    evidenceConfig: [
      {
        id: "receipt-photo",
        type: "Photo",
        required: true,
        minCount: 1,
        label: "Foto de recepción",
        guidance: "Captura los paquetes y su condición sin incluir datos personales.",
      },
      { id: "receipt-time", type: "Timestamp", required: true, label: "Fecha y hora" },
      { id: "receipt-signature", type: "Signature", required: true, label: "Firma de recepción" },
    ],
    formConfig: [
      { id: "deliveryReference", type: "text", label: "Referencia de entrega", required: true },
      { id: "expectedQuantity", type: "number", label: "Cantidad esperada", required: true },
      { id: "receivedQuantity", type: "number", label: "Cantidad recibida", required: true },
      { id: "damagedQuantity", type: "number", label: "Paquetes con daño", required: true },
      {
        id: "condition",
        type: "select",
        label: "Condición general",
        required: true,
        options: ["Conforme", "Con observaciones", "Rechazada"],
      },
      { id: "comments", type: "textarea", label: "Comentarios o diferencias" },
    ],
    supervisors,
    operators,
    channels: ["System", "Push"],
    preAlertMinutes: 30,
    requiresValidation: true,
    activationMode: "OnDemand",
    estimatedMinutes: 12,
    safetyInstructions: ["No firmar como conforme si existen diferencias sin registrar."],
  },
  {
    id: "retail-opening",
    name: "Apertura, imagen y condición de tienda",
    description:
      "Confirma acceso, limpieza, presentación, climatización y preparación operativa antes de abrir.",
    category: "Apertura y presentación",
    priority: "High",
    status: "Active",
    branches: plants,
    recurrence: "Daily",
    schedule: [{ hour: "09:00", tolerance: 15 }],
    evidenceConfig: commonStoreEvidence,
    formConfig: [
      {
        id: "access",
        type: "yesno",
        label: "Acceso y cortinas operan correctamente",
        required: true,
      },
      { id: "presentation", type: "rating", label: "Presentación de sala", required: true },
      { id: "temperature", type: "number", label: "Temperatura de sala (°C)", required: true },
      {
        id: "incident",
        type: "yesno",
        label: "¿Requiere apoyo del centro de soporte?",
        required: true,
      },
    ],
    supervisors: supervisors,
    operators: operators,
    channels: ["System", "Push", "WhatsApp"],
    preAlertMinutes: 30,
    requiresValidation: true,
    activationMode: "Recurring",
    estimatedMinutes: 18,
    safetyInstructions: ["No intervenir tableros eléctricos ni equipos energizados."],
  },
  {
    id: "retail-cleaning",
    name: "Limpieza, orden y presentación del día",
    description: "Verifica probadores, sala de venta, escaparate y back office.",
    category: "Limpieza y orden",
    priority: "Medium",
    status: "Active",
    branches: plants,
    recurrence: "Daily",
    schedule: [{ hour: "13:00", tolerance: 30 }],
    evidenceConfig: commonStoreEvidence,
    formConfig: [
      { id: "floor", type: "yesno", label: "Piso y mobiliario limpios", required: true },
      { id: "fitting", type: "yesno", label: "Probadores listos", required: true },
    ],
    supervisors,
    operators,
    channels: ["System"],
    preAlertMinutes: 15,
    requiresValidation: false,
    activationMode: "Recurring",
    estimatedMinutes: 12,
  },
  {
    id: "retail-sales-intentions",
    name: "Ventas, intenciones y oportunidades",
    description: "Registra afluencia, intenciones de compra, barreras y oportunidades de servicio.",
    category: "Ventas e intenciones",
    priority: "Medium",
    status: "Active",
    branches: plants,
    recurrence: "Daily",
    schedule: [{ hour: "18:30", tolerance: 30 }],
    evidenceConfig: [{ id: "timestamp", type: "Timestamp", required: true }],
    formConfig: [
      { id: "visitors", type: "number", label: "Visitantes atendidos", required: true },
      { id: "intentions", type: "number", label: "Intenciones de compra", required: true },
      { id: "barriers", type: "textarea", label: "Barreras y oportunidades" },
    ],
    supervisors,
    operators,
    channels: ["System"],
    preAlertMinutes: 20,
    requiresValidation: false,
    activationMode: "Recurring",
    estimatedMinutes: 8,
  },
  {
    id: "retail-measurements",
    name: "Toma de medidas y seguimiento de cliente",
    description:
      "Estandariza la captura de medidas y el seguimiento del servicio sin exponer datos sensibles.",
    category: "Medidas y servicio",
    priority: "Medium",
    status: "Active",
    branches: plants,
    recurrence: "Once",
    schedule: [{ hour: "12:00", tolerance: 60 }],
    evidenceConfig: [{ id: "timestamp", type: "Timestamp", required: true }],
    formConfig: [
      { id: "reference", type: "text", label: "Referencia de servicio", required: true },
      { id: "measurements", type: "textarea", label: "Medidas registradas", required: true },
    ],
    supervisors,
    operators,
    channels: ["System"],
    preAlertMinutes: 20,
    requiresValidation: true,
    activationMode: "OnDemand",
    estimatedMinutes: 15,
  },
  {
    id: "retail-hvac-diagnostic",
    name: "Diagnóstico seguro de climatización",
    description:
      "Guía verificaciones no invasivas antes de decidir soporte interno o intervención de proveedor.",
    category: "Climatización",
    priority: "High",
    status: "Active",
    branches: plants,
    recurrence: "Once",
    schedule: [{ hour: "10:00", tolerance: 30 }],
    evidenceConfig: commonStoreEvidence,
    formConfig: [
      { id: "display", type: "yesno", label: "El control está encendido", required: true },
      { id: "setpoint", type: "number", label: "Temperatura configurada (°C)", required: true },
      {
        id: "airflow",
        type: "select",
        label: "Flujo de aire",
        required: true,
        options: ["Normal", "Bajo", "Sin flujo"],
      },
      { id: "resolved", type: "yesno", label: "¿Se restableció la climatización?", required: true },
    ],
    supervisors: ["Elena Ríos"],
    operators: ["Valeria Santos", "Diego Castro"],
    channels: ["System", "WhatsApp"],
    preAlertMinutes: 5,
    requiresValidation: true,
    activationMode: "Triggered",
    triggerEvent: "Solicitud de soporte de climatización reportada",
    assetIds: ["CLM-02"],
    estimatedMinutes: 10,
    safetyInstructions: [
      "Realizar únicamente verificaciones visibles y ajustes del control.",
      "No abrir gabinetes, desmontar protecciones ni intervenir conexiones eléctricas.",
    ],
  },
];

export const seedSchedules: Schedule[] = [
  {
    id: "sch-opening-north",
    protocolId: "retail-opening",
    date: openingWindow.format("YYYY-MM-DD"),
    hour: openingWindow.format("HH:mm"),
    tolerance: 15,
    operator: "Valeria Santos",
    status: "Pending",
    assetId: "CLM-02",
    plant: "Boutique Norte",
    workOrder: "OP-BN-0819",
    siteLabel: "Boutique Norte",
    priority: "High",
    notes: "Apertura y condición operativa de la sucursal.",
    createdAt: demoNow().subtract(1, "day").toISOString(),
  },
  {
    id: "sch-network-valle",
    protocolId: "retail-hvac-diagnostic",
    date: today,
    hour: "11:30",
    tolerance: 30,
    operator: "Diego Castro",
    status: "InProgress",
    assetId: "NET-03",
    plant: "Boutique Valle",
    workOrder: "SOP-BV-031",
    siteLabel: "Boutique Valle",
    priority: "High",
  },
  {
    id: "sch-light-oriente",
    protocolId: "retail-hvac-diagnostic",
    date: serviceWindow.format("YYYY-MM-DD"),
    hour: serviceWindow.format("HH:mm"),
    tolerance: 30,
    operator: "Diego Castro",
    status: "Pending",
    assetId: "LGT-11",
    plant: "Boutique Oriente",
    workOrder: "SOP-BO-019",
    siteLabel: "Boutique Oriente",
    priority: "Medium",
  },
  {
    id: "sch-closing-west",
    protocolId: "retail-sales-intentions",
    date: yesterday,
    hour: "18:30",
    tolerance: 30,
    operator: "Camila Torres",
    status: "Completed",
    plant: "Boutique Poniente",
    workOrder: "OP-BP-0818",
    siteLabel: "Boutique Poniente",
    priority: "Medium",
  },
];

export const seedReservations: ResourceReservation[] = [];

export const seedExecutions: Execution[] = [
  {
    id: "exe-closing-west",
    scheduleId: "sch-closing-west",
    protocolId: "retail-sales-intentions",
    startAt: demoNow().subtract(1, "day").hour(18).minute(29).toISOString(),
    endAt: demoNow().subtract(1, "day").hour(18).minute(36).toISOString(),
    operator: "Camila Torres",
    status: "Validated",
    evidences: [],
    formAnswers: { visitors: 86, intentions: 31, barriers: "Sin incidencias operativas." },
    score: 96,
  },
];

export const seedIncidents: Incident[] = [];

export const seedNotifications: Notification[] = [
  {
    id: "not-retail-receipt",
    type: "Assignment",
    channel: "Push",
    actor: "Centro de distribución",
    recipientRole: "operator",
    recipient: "Valeria Santos",
    source: "Automatic",
    event: "Recepción programada",
    message: "Tienes una recepción de 48 paquetes asignada para Boutique Norte.",
    actionLabel: "Atender recepción",
    status: "Sent",
    createdAt: demoNow().subtract(8, "minute").toISOString(),
  },
  {
    id: "not-retail-1",
    type: "Assignment",
    channel: "Push",
    actor: "Gerencia de sucursales",
    recipientRole: "operator",
    recipient: "Valeria Santos",
    source: "Automatic",
    event: "Programa publicado",
    message: "Tu protocolo de apertura está listo para Boutique Norte.",
    actionLabel: "Abrir programa",
    status: "Read",
    createdAt: demoNow().subtract(35, "minute").toISOString(),
  },
  {
    id: "not-retail-2",
    type: "Escalation",
    channel: "System",
    actor: "Centro de soporte",
    recipientRole: "admin",
    source: "Automatic",
    event: "Caso P2 en diagnóstico",
    message: "Boutique Valle requiere seguimiento de conectividad.",
    actionLabel: "Ver solicitud",
    status: "Sent",
    createdAt: demoNow().subtract(18, "minute").toISOString(),
  },
];

export const seedOperationalFlows: OperationalFlow[] = [
  {
    id: "flow-store-support",
    name: "Operación de tienda y soporte contextual",
    description:
      "Conecta el programa de sucursal con diagnóstico, intervención y cierre confirmado.",
    assetId: "CLM-02",
    status: "Running",
    steps: [
      { id: "publish", name: "Programa publicado", mode: "Linear", status: "Completed" },
      {
        id: "execute",
        name: "Protocolo en tienda",
        protocolId: "retail-opening",
        mode: "Linear",
        status: "Running",
      },
      {
        id: "diagnose",
        name: "Diagnóstico de soporte",
        protocolId: "retail-hvac-diagnostic",
        mode: "Linear",
        status: "Waiting",
      },
      { id: "intervene", name: "Intervención especializada", mode: "Linear", status: "Waiting" },
      { id: "confirm", name: "Confirmación y cierre", mode: "Linear", status: "Waiting" },
    ],
  },
];

export const seedServiceRequests: ServiceRequest[] = [];

export const seedStoreAssignments: StoreAssignment[] = [
  {
    id: "RTL-ASG-1028",
    protocolId: "retail-merchandise-receipt",
    storeId: "store-north",
    storeLabel: "Boutique Norte",
    responsible: "Valeria Santos",
    dueAt: demoNow().add(2, "hour").startOf("hour").toISOString(),
    status: "Assigned",
    protocolVersion: "1.0",
    progress: 0,
    requiresValidation: true,
    comments: "Entrega OC-DEMO-2481 · Distribución Norte Demo · 48 paquetes esperados.",
  },
  {
    id: "RTL-ASG-1024",
    protocolId: "retail-opening",
    storeId: "store-north",
    storeLabel: "Boutique Norte",
    responsible: "Valeria Santos",
    dueAt: openingWindow.add(15, "minute").toISOString(),
    status: "Acknowledged",
    protocolVersion: "3.2",
    progress: 12,
    scheduleId: "sch-opening-north",
    requiresValidation: true,
  },
  {
    id: "RTL-ASG-1025",
    protocolId: "retail-cleaning",
    storeId: "store-center",
    storeLabel: "Boutique Centro",
    responsible: "Sergio Luna",
    dueAt: demoNow().hour(13).minute(30).toISOString(),
    status: "Assigned",
    protocolVersion: "2.1",
    progress: 0,
    requiresValidation: false,
  },
  {
    id: "RTL-ASG-1026",
    protocolId: "retail-sales-intentions",
    storeId: "store-west",
    storeLabel: "Boutique Poniente",
    responsible: "Camila Torres",
    dueAt: demoNow().subtract(1, "day").hour(19).toISOString(),
    status: "Completed",
    protocolVersion: "1.8",
    progress: 100,
    scheduleId: "sch-closing-west",
    requiresValidation: false,
    completedAt: demoNow().subtract(1, "day").hour(18).minute(36).toISOString(),
  },
  {
    id: "RTL-ASG-1027",
    protocolId: "retail-cleaning",
    storeId: "store-airport",
    storeLabel: "Boutique Aeropuerto",
    responsible: "Camila Torres",
    dueAt: demoNow().hour(13).minute(30).toISOString(),
    status: "Draft",
    protocolVersion: "2.1",
    progress: 0,
    requiresValidation: false,
  },
];

export const seedSupportCases: SupportCase[] = [
  {
    id: "RTL-SUP-2048",
    title: "Temperatura fuera de rango en sala de ventas",
    storeId: "store-north",
    storeLabel: "Boutique Norte",
    areaLabel: "Sala de ventas",
    assetId: "CLM-02",
    sourceAssignmentId: "RTL-ASG-1024",
    sourceProtocolId: "retail-opening",
    symptom: "La sala registra 27.8 °C y el flujo de aire es bajo.",
    operationalImpact: "Confort de clientes y equipo de tienda afectado durante la apertura.",
    suggestedPriority: "P2",
    status: "Draft",
    route: "Unassigned",
    currentOwner: "Valeria Santos",
    updates: [
      {
        id: "upd-2048-draft",
        at: demoNow().subtract(4, "minute").toISOString(),
        actor: "Valeria Santos",
        label: "Desviación detectada",
        detail: "El caso quedó preparado dentro del protocolo; aún no se envía a soporte.",
      },
    ],
  },
  {
    id: "RTL-SUP-2039",
    title: "Intermitencia de conectividad en caja",
    storeId: "store-valle",
    storeLabel: "Boutique Valle",
    areaLabel: "Caja",
    assetId: "NET-03",
    symptom: "La terminal pierde conexión durante cobros.",
    operationalImpact: "Cobros con espera y riesgo de abandono.",
    suggestedPriority: "P2",
    confirmedPriority: "P2",
    status: "Diagnosing",
    route: "Internal",
    currentOwner: "Diego Castro",
    reportedAt: demoNow().subtract(52, "minute").toISOString(),
    acknowledgementDueAt: demoNow().subtract(37, "minute").toISOString(),
    resolutionTargetAt: demoNow().add(3, "hour").toISOString(),
    diagnosticProtocolId: "retail-hvac-diagnostic",
    updates: [
      {
        id: "upd-2039-report",
        at: demoNow().subtract(52, "minute").toISOString(),
        actor: "Boutique Valle",
        label: "Solicitud reportada",
        detail: "Se adjuntaron prueba de red y foto del indicador.",
      },
      {
        id: "upd-2039-diagnosis",
        at: demoNow().subtract(31, "minute").toISOString(),
        actor: "Diego Castro",
        label: "Diagnóstico remoto iniciado",
        detail: "La tienda ejecuta verificaciones seguras guiadas.",
      },
    ],
  },
  {
    id: "RTL-SUP-2027",
    title: "Iluminación parcial en escaparate",
    storeId: "store-east",
    storeLabel: "Boutique Oriente",
    areaLabel: "Escaparate",
    assetId: "LGT-11",
    symptom: "Dos módulos del escaparate no encienden.",
    operationalImpact: "Presentación exterior incompleta.",
    suggestedPriority: "P3",
    confirmedPriority: "P3",
    status: "ExternalAssigned",
    route: "External",
    currentOwner: "Servicios Lumina Demo",
    reportedAt: demoNow().subtract(3, "hour").toISOString(),
    acknowledgementDueAt: demoNow().subtract(2, "hour").toISOString(),
    resolutionTargetAt: demoNow().add(5, "hour").toISOString(),
    interventionId: "RTL-INT-301",
    updates: [
      {
        id: "upd-2027-report",
        at: demoNow().subtract(3, "hour").toISOString(),
        actor: "Boutique Oriente",
        label: "Solicitud reportada",
        detail: "La falla se identificó durante el protocolo de apertura.",
      },
      {
        id: "upd-2027-vendor",
        at: demoNow().subtract(2, "hour").toISOString(),
        actor: "Elena Ríos",
        label: "Proveedor asignado",
        detail: "Visita confirmada dentro de la ventana operativa.",
      },
    ],
  },
  {
    id: "RTL-SUP-2014",
    title: "Impresora de tickets sin papel detectado",
    storeId: "store-west",
    storeLabel: "Boutique Poniente",
    areaLabel: "Caja",
    assetId: "PRN-06",
    symptom: "El equipo no reconocía el consumible.",
    operationalImpact: "Comprobantes impresos temporalmente en caja alterna.",
    suggestedPriority: "P3",
    confirmedPriority: "P3",
    status: "Closed",
    route: "Internal",
    currentOwner: "Centro de soporte",
    reportedAt: demoNow().subtract(1, "day").toISOString(),
    acknowledgementDueAt: demoNow().subtract(1, "day").add(15, "minute").toISOString(),
    resolutionTargetAt: demoNow().subtract(1, "day").add(2, "hour").toISOString(),
    storeConfirmedAt: demoNow().subtract(23, "hour").toISOString(),
    closedAt: demoNow().subtract(22, "hour").toISOString(),
    resolutionSummary: "Se recolocó el rollo y se validó la impresión con la tienda.",
    updates: [],
  },
];

export const seedSupportInterventions: SupportIntervention[] = [
  {
    id: "RTL-INT-301",
    caseId: "RTL-SUP-2027",
    route: "External",
    assignee: "Servicios Lumina Demo",
    specialty: "Iluminación comercial",
    scheduledAt: demoNow().add(2, "hour").toISOString(),
    status: "Scheduled",
  },
];
