import dayjs from "dayjs";
import { demoNow } from "../../clock";
import type {
  Asset,
  Execution,
  Incident,
  InventoryItem,
  MaintenanceTool,
  Notification,
  OperationalFlow,
  Person,
  Protocol,
  ResourceReservation,
  Schedule,
  Skill,
} from "../../../ove/types";

const PLANT = "Planta de Alambres";
const today = demoNow().format("YYYY-MM-DD");
const tomorrow = demoNow().add(1, "day").format("YYYY-MM-DD");

type AssetSeed = Pick<Asset, "id" | "name" | "family" | "area"> &
  Partial<Pick<Asset, "criticality" | "status" | "availability" | "health" | "runtimeHours">>;

function createAsset(seed: AssetSeed, lastServiceDays = 30): Asset {
  return {
    plant: PLANT,
    criticality: seed.criticality ?? "Medium",
    status: seed.status ?? "Available",
    availability: seed.availability ?? 97.2,
    health: seed.health ?? 90,
    runtimeHours: seed.runtimeHours ?? 7200,
    lastService: demoNow().subtract(lastServiceDays, "day").toISOString(),
    ...seed,
  };
}

export const seedAssets: Asset[] = [
  createAsset(
    {
      id: "LAM-01",
      name: "Laminadora 1",
      family: "Laminadoras",
      area: "Laminado",
      criticality: "High",
    },
    18,
  ),
  createAsset(
    {
      id: "LAM-02",
      name: "Laminadora 2",
      family: "Laminadoras",
      area: "Laminado",
      status: "Maintenance",
      health: 81,
    },
    42,
  ),
  createAsset(
    {
      id: "TRF-01",
      name: "Trefiladora 1",
      family: "Trefiladoras",
      area: "Trefilado para Recocido y Clavo",
      criticality: "High",
    },
    22,
  ),
  createAsset(
    {
      id: "TRF-02",
      name: "Trefiladora 2",
      family: "Trefiladoras",
      area: "Trefilado para Recocido y Clavo",
      criticality: "High",
    },
    16,
  ),
  createAsset(
    {
      id: "TRF-03",
      name: "Trefiladora 3 · 9 pasos",
      family: "Trefiladoras",
      area: "Trefilado para Recocido y Clavo",
      criticality: "Critical",
      status: "Risk",
      availability: 89.6,
      health: 68,
      runtimeHours: 12480,
    },
    67,
  ),
  ...Array.from({ length: 5 }, (_, index) =>
    createAsset(
      {
        id: `CLV-0${index + 1}`,
        name: `Clavera ${index + 1}`,
        family: "Claveras",
        area: "Clavo",
        criticality: index < 2 ? "High" : "Medium",
        status: index === 3 ? "Maintenance" : "Available",
        health: index === 3 ? 79 : 91 - index,
      },
      12 + index * 6,
    ),
  ),
  createAsset(
    {
      id: "HOR-01",
      name: "Horno 1",
      family: "Hornos de recocido",
      area: "Recocido",
      criticality: "Critical",
    },
    25,
  ),
  createAsset(
    {
      id: "HOR-02",
      name: "Horno 2",
      family: "Hornos de recocido",
      area: "Recocido",
      criticality: "Critical",
    },
    31,
  ),
  createAsset(
    {
      id: "MAL-01",
      name: "Malla 1",
      family: "Electrosoldado",
      area: "Electrosoldado",
      criticality: "High",
    },
    14,
  ),
  createAsset(
    {
      id: "MAL-02",
      name: "Malla 2",
      family: "Electrosoldado",
      area: "Electrosoldado",
      criticality: "High",
    },
    20,
  ),
  createAsset(
    {
      id: "END-01",
      name: "Enderezadora 1",
      family: "Enderezadoras",
      area: "Varilla 6000",
      criticality: "High",
    },
    11,
  ),
  ...Array.from({ length: 3 }, (_, index) =>
    createAsset(
      {
        id: `TRS-0${index + 1}`,
        name: `Transformador ${index + 1}`,
        family: "Transformadores",
        area: "Servicios Generales",
        criticality: "Critical",
      },
      28 + index * 9,
    ),
  ),
  ...Array.from({ length: 2 }, (_, index) =>
    createAsset(
      {
        id: `CMP-0${index + 1}`,
        name: `Compresor ${index + 1}`,
        family: "Compresores",
        area: "Servicios Generales",
        criticality: "High",
      },
      19 + index * 13,
    ),
  ),
  ...Array.from({ length: 4 }, (_, index) =>
    createAsset(
      {
        id: `GRU-0${index + 1}`,
        name: `Grúa ${index + 1}`,
        family: "Grúas",
        area: "Servicios Generales",
        criticality: "High",
        status: index === 2 ? "Risk" : "Available",
        health: index === 2 ? 74 : 92 - index,
      },
      17 + index * 7,
    ),
  ),
  createAsset(
    {
      id: "TEN-01",
      name: "Torre de Enfriamiento",
      family: "Enfriamiento",
      area: "Servicios Generales",
      criticality: "High",
    },
    21,
  ),
  createAsset(
    {
      id: "CHL-01",
      name: "Chiller",
      family: "Enfriamiento",
      area: "Servicios Generales",
      criticality: "High",
    },
    24,
  ),
];

export const seedSkills: Skill[] = [
  { id: "sk-wire", name: "Mantenimiento de trefiladoras", category: "Technical" },
  { id: "sk-mechanical", name: "Diagnóstico y ajuste mecánico", category: "Technical" },
  { id: "sk-electrical", name: "Diagnóstico eléctrico industrial", category: "Technical" },
  { id: "sk-condition", name: "Medición de vibración y temperatura", category: "Technical" },
  { id: "sk-loto", name: "Bloqueo y etiquetado LOTO", category: "Safety" },
  { id: "sk-height", name: "Trabajo seguro en alturas", category: "Safety" },
];

export const seedPeople: Person[] = [
  {
    id: "per-eduardo",
    name: "Eduardo Morales",
    role: "Technician",
    plant: PLANT,
    shift: "Morning",
    skillIds: ["sk-wire", "sk-mechanical", "sk-electrical", "sk-condition", "sk-loto"],
    certificationValidUntil: demoNow().add(10, "month").format("YYYY-MM-DD"),
    status: "Available",
  },
  {
    id: "per-fernanda",
    name: "Fernanda Ruiz",
    role: "Technician",
    plant: PLANT,
    shift: "Morning",
    skillIds: ["sk-wire", "sk-mechanical", "sk-electrical", "sk-loto"],
    status: "Assigned",
  },
  {
    id: "per-carlos",
    name: "Carlos Neri",
    role: "Technician",
    plant: PLANT,
    shift: "Morning",
    skillIds: ["sk-mechanical", "sk-loto"],
    status: "Available",
  },
  {
    id: "per-alma",
    name: "Alma Ortega",
    role: "Technician",
    plant: PLANT,
    shift: "Afternoon",
    skillIds: ["sk-electrical", "sk-loto"],
    status: "Available",
  },
  {
    id: "per-miguel",
    name: "Miguel Salas",
    role: "Supervisor",
    plant: PLANT,
    shift: "Morning",
    skillIds: ["sk-wire", "sk-mechanical", "sk-electrical", "sk-condition", "sk-loto"],
    status: "Available",
  },
  ...[
    ["per-laura", "Laura Vázquez", ["sk-electrical", "sk-condition", "sk-loto"]],
    ["per-andres", "Andrés Peña", ["sk-electrical", "sk-loto"]],
    ["per-sofia", "Sofía Campos", ["sk-electrical", "sk-loto"]],
    ["per-daniel", "Daniel Ríos", ["sk-mechanical", "sk-condition", "sk-loto"]],
    ["per-jorge", "Jorge Luna", ["sk-mechanical", "sk-loto"]],
    ["per-mariana", "Mariana Torres", ["sk-mechanical", "sk-height", "sk-loto"]],
  ].map(([id, name, skillIds], index) => ({
    id: id as string,
    name: name as string,
    role: "Technician" as const,
    plant: PLANT,
    shift: index > 2 ? ("Afternoon" as const) : ("Morning" as const),
    skillIds: skillIds as string[],
    status: "Available" as const,
  })),
];

export const seedTools: MaintenanceTool[] = [
  {
    id: "tool-loto",
    name: "Kit LOTO industrial",
    serial: "SIM-LOTO-01",
    plant: PLANT,
    location: "Pañol de mantenimiento",
    status: "Reserved",
  },
  {
    id: "tool-vibration",
    name: "Analizador de vibración",
    serial: "SIM-AV-03",
    plant: PLANT,
    location: "Laboratorio de mantenimiento",
    status: "Reserved",
    calibrationValidUntil: demoNow().add(7, "month").format("YYYY-MM-DD"),
  },
  {
    id: "tool-thermal",
    name: "Cámara termográfica",
    serial: "SIM-CT-08",
    plant: PLANT,
    location: "Laboratorio de mantenimiento",
    status: "Available",
    calibrationValidUntil: demoNow().add(6, "month").format("YYYY-MM-DD"),
  },
  {
    id: "tool-meter",
    name: "Multímetro industrial",
    serial: "SIM-MD-14",
    plant: PLANT,
    location: "Pañol de mantenimiento",
    status: "Available",
    calibrationValidUntil: demoNow().add(9, "month").format("YYYY-MM-DD"),
  },
  {
    id: "tool-torque",
    name: "Torquímetro digital",
    serial: "SIM-TQ-22",
    plant: PLANT,
    location: "Pañol de mantenimiento",
    status: "Available",
    calibrationValidUntil: demoNow().add(5, "month").format("YYYY-MM-DD"),
  },
];

export const seedInventory: InventoryItem[] = [
  {
    id: "mat-clean",
    sku: "SIM-CLN-01",
    name: "Consumibles de limpieza industrial",
    unit: "kit",
    plant: PLANT,
    warehouse: "Almacén MRO",
    onHand: 18,
    reserved: 1,
    quarantine: 0,
    reorderPoint: 5,
  },
  {
    id: "mat-lubricant",
    sku: "SIM-LUB-01",
    name: "Lubricante industrial demostrativo",
    unit: "L",
    plant: PLANT,
    warehouse: "Almacén MRO",
    onHand: 32,
    reserved: 2,
    quarantine: 0,
    reorderPoint: 8,
  },
  {
    id: "mat-fasteners",
    sku: "SIM-FST-01",
    name: "Juego de fijaciones de demostración",
    unit: "jgo",
    plant: PLANT,
    warehouse: "Almacén MRO",
    onHand: 12,
    reserved: 0,
    quarantine: 0,
    reorderPoint: 4,
  },
];

const wirePhotoManifest = [
  {
    id: "photo-before",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Condición inicial del equipo",
    phase: "Pre-intervention" as const,
    guidance: "Muestra el activo completo, sus guardas y la identificación de la orden.",
    referenceData: "maintenance/wire-drawing-before.jpg",
    captureData: "maintenance/wire-drawing-before.jpg",
    aiValidation: false,
    humanRating: true,
  },
  {
    id: "photo-during",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Inspección e intervención",
    phase: "Intervention" as const,
    guidance: "Muestra el punto inspeccionado y el trabajo realizado en condición segura.",
    referenceData: "maintenance/wire-drawing-before.jpg",
    captureData: "maintenance/wire-drawing-during.jpg",
    aiValidation: false,
    humanRating: true,
  },
  {
    id: "photo-after",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Condición final y guardas restablecidas",
    phase: "Post-intervention" as const,
    guidance: "Muestra el equipo cerrado y listo para la validación de liberación.",
    referenceData: "maintenance/wire-drawing-before.jpg",
    captureData: "maintenance/wire-drawing-after.jpg",
    aiValidation: false,
    humanRating: true,
  },
];

export const seedProtocols: Protocol[] = [
  {
    id: "p-wire-condition",
    name: "Diagnóstico correctivo · Trefiladora multipaso",
    description:
      "Inspección demostrativa por ruido o vibración reportada, con seguridad, mediciones, evidencia y prueba operativa.",
    category: "Correctivo",
    priority: "Critical",
    status: "Active",
    branches: [PLANT],
    recurrence: "Once",
    schedule: [{ hour: "10:30", tolerance: 20 }],
    evidenceConfig: [
      { id: "arrival", type: "Timestamp", required: true, label: "Inicio de intervención" },
      ...wirePhotoManifest,
      { id: "signature", type: "Signature", required: true, label: "Firma del técnico" },
    ],
    formConfig: [
      {
        id: "loto",
        type: "yesno",
        label: "Bloqueo y condición segura confirmados",
        required: true,
      },
      {
        id: "diagnosis",
        type: "textarea",
        label: "Diagnóstico de la condición reportada",
        required: true,
      },
      { id: "temperature", type: "number", label: "Temperatura observada (°C)", required: true },
      { id: "vibration", type: "number", label: "Vibración observada (mm/s)", required: true },
      {
        id: "guards",
        type: "select",
        label: "Condición de guardas",
        required: true,
        options: ["Correcta", "Ajustada durante la intervención", "Requiere seguimiento"],
      },
      {
        id: "lubrication",
        type: "select",
        label: "Lubricación y enfriamiento",
        required: true,
        options: ["Sin desviaciones visibles", "Ajuste realizado", "Requiere seguimiento"],
      },
      {
        id: "test",
        type: "select",
        label: "Resultado de prueba operativa",
        required: true,
        options: ["Operación estable", "Liberación con seguimiento", "No liberar"],
      },
      { id: "notes", type: "comment", label: "Observaciones del técnico" },
    ],
    supervisors: ["Miguel Salas"],
    operators: ["Eduardo Morales", "Fernanda Ruiz"],
    channels: ["System", "Push"],
    preAlertMinutes: 30,
    requiresValidation: true,
    activationMode: "Triggered",
    triggerEvent: "Reporte de ruido o vibración fuera de la condición habitual",
    assetIds: ["TRF-03"],
    materials: [
      "Consumibles de limpieza · hasta 1 kit",
      "Lubricante demostrativo · según hallazgo",
    ],
    safetyInstructions: [
      "Aplicar bloqueo y etiquetado antes de abrir guardas",
      "Confirmar ausencia de movimiento y energía residual",
      "Restablecer guardas antes de la prueba operativa",
    ],
    estimatedMinutes: 90,
    allowRescheduling: true,
    requiredSkillIds: ["sk-wire", "sk-mechanical", "sk-electrical", "sk-condition", "sk-loto"],
    requiredToolIds: ["tool-loto", "tool-vibration", "tool-thermal"],
    materialRequirements: [
      { inventoryItemId: "mat-clean", mode: "Variable", min: 0, max: 1 },
      { inventoryItemId: "mat-lubricant", mode: "Variable", min: 0, max: 2 },
    ],
    workConceptTemplates: [
      {
        code: "INS-TRF",
        description: "Inspección y diagnóstico de trefiladora",
        unit: "SERV",
        quantity: 1,
      },
      { code: "PRB-OP", description: "Prueba operativa y liberación", unit: "SERV", quantity: 1 },
    ],
  },
  {
    id: "p-compressor-preventive",
    name: "Preventivo · Compresor",
    description: "Rutina demostrativa de inspección, limpieza y condición operativa.",
    category: "Preventivo",
    priority: "High",
    status: "Active",
    branches: [PLANT],
    recurrence: "Monthly",
    schedule: [{ hour: "09:00", tolerance: 30 }],
    evidenceConfig: [{ type: "Timestamp", required: true, label: "Registro de intervención" }],
    formConfig: [{ id: "condition", type: "comment", label: "Condición general", required: true }],
    supervisors: ["Miguel Salas"],
    operators: ["Daniel Ríos", "Jorge Luna"],
    channels: ["System"],
    preAlertMinutes: 60,
    requiresValidation: false,
    activationMode: "Recurring",
    triggerEvent: "Plan preventivo mensual",
    assetIds: ["CMP-01", "CMP-02"],
    estimatedMinutes: 45,
    allowRescheduling: true,
    requiredSkillIds: ["sk-mechanical", "sk-loto"],
    requiredToolIds: ["tool-thermal"],
  },
  {
    id: "p-electrical-inspection",
    name: "Inspección eléctrica · Transformador",
    description: "Verificación demostrativa de condición eléctrica y térmica.",
    category: "Inspección",
    priority: "High",
    status: "Active",
    branches: [PLANT],
    recurrence: "Monthly",
    schedule: [{ hour: "08:00", tolerance: 20 }],
    evidenceConfig: [{ type: "Timestamp", required: true, label: "Registro de inspección" }],
    formConfig: [
      { id: "thermal", type: "comment", label: "Hallazgos de inspección", required: true },
    ],
    supervisors: ["Miguel Salas"],
    operators: ["Laura Vázquez", "Andrés Peña", "Sofía Campos"],
    channels: ["System"],
    preAlertMinutes: 45,
    requiresValidation: true,
    activationMode: "Recurring",
    triggerEvent: "Programa de inspección eléctrica",
    assetIds: ["TRS-01", "TRS-02", "TRS-03"],
    estimatedMinutes: 40,
    allowRescheduling: true,
    requiredSkillIds: ["sk-electrical", "sk-condition", "sk-loto"],
    requiredToolIds: ["tool-thermal", "tool-meter"],
  },
  {
    id: "p-crane-safety",
    name: "Revisión de seguridad · Grúa",
    description: "Inspección visual demostrativa previa a una revisión técnica especializada.",
    category: "Seguridad",
    priority: "High",
    status: "Active",
    branches: [PLANT],
    recurrence: "Weekly",
    schedule: [{ hour: "07:30", tolerance: 15 }],
    evidenceConfig: [{ type: "Timestamp", required: true, label: "Registro de revisión" }],
    formConfig: [{ id: "findings", type: "comment", label: "Hallazgos visibles", required: true }],
    supervisors: ["Miguel Salas"],
    operators: ["Mariana Torres"],
    channels: ["System"],
    preAlertMinutes: 30,
    requiresValidation: true,
    activationMode: "Recurring",
    triggerEvent: "Programa semanal de seguridad",
    assetIds: ["GRU-01", "GRU-02", "GRU-03", "GRU-04"],
    estimatedMinutes: 30,
    allowRescheduling: true,
    requiredSkillIds: ["sk-mechanical", "sk-height", "sk-loto"],
  },
  {
    id: "p-furnace-thermal",
    name: "Verificación térmica · Horno",
    description: "Registro demostrativo de condición térmica y observaciones de mantenimiento.",
    category: "Preventivo",
    priority: "High",
    status: "Active",
    branches: [PLANT],
    recurrence: "Monthly",
    schedule: [{ hour: "11:00", tolerance: 20 }],
    evidenceConfig: [{ type: "Timestamp", required: true, label: "Registro de verificación" }],
    formConfig: [
      { id: "condition", type: "comment", label: "Condición observada", required: true },
    ],
    supervisors: ["Miguel Salas"],
    operators: ["Eduardo Morales", "Laura Vázquez"],
    channels: ["System"],
    preAlertMinutes: 45,
    requiresValidation: true,
    activationMode: "Recurring",
    triggerEvent: "Plan preventivo térmico",
    assetIds: ["HOR-01", "HOR-02"],
    estimatedMinutes: 45,
    allowRescheduling: true,
    requiredSkillIds: ["sk-electrical", "sk-condition", "sk-loto"],
    requiredToolIds: ["tool-thermal"],
  },
  {
    id: "p-mesh-preventive",
    name: "Preventivo · Línea de electrosoldado",
    description: "Inspección demostrativa de condición mecánica y eléctrica.",
    category: "Preventivo",
    priority: "Medium",
    status: "Active",
    branches: [PLANT],
    recurrence: "Monthly",
    schedule: [{ hour: "13:00", tolerance: 30 }],
    evidenceConfig: [{ type: "Timestamp", required: true, label: "Registro de intervención" }],
    formConfig: [{ id: "condition", type: "comment", label: "Condición general", required: true }],
    supervisors: ["Miguel Salas"],
    operators: ["Fernanda Ruiz"],
    channels: ["System"],
    preAlertMinutes: 60,
    requiresValidation: false,
    activationMode: "Recurring",
    triggerEvent: "Plan preventivo mensual",
    assetIds: ["MAL-01", "MAL-02"],
    estimatedMinutes: 50,
    allowRescheduling: true,
    requiredSkillIds: ["sk-mechanical", "sk-electrical", "sk-loto"],
  },
];

export const seedSchedules: Schedule[] = [
  {
    id: "s-wire-main",
    protocolId: "p-wire-condition",
    date: today,
    hour: "10:30",
    tolerance: 20,
    operator: "Eduardo Morales",
    status: "Pending",
    assetId: "TRF-03",
    plant: PLANT,
    workOrder: "OT-ALM-2408",
    serviceReference: "COND-TRF-003",
    siteLabel: "Trefilado para Recocido y Clavo",
    toolIds: ["tool-loto", "tool-vibration", "tool-thermal"],
    materialAllocations: [
      { inventoryItemId: "mat-clean", mode: "Variable", min: 0, max: 1, reservedQuantity: 1 },
      { inventoryItemId: "mat-lubricant", mode: "Variable", min: 0, max: 2, reservedQuantity: 2 },
    ],
    eligibilityValidated: true,
    notes: "Escenario demostrativo: reporte de ruido y vibración fuera de la condición habitual.",
  },
  {
    id: "s-compressor",
    protocolId: "p-compressor-preventive",
    date: today,
    hour: "09:00",
    tolerance: 30,
    operator: "Daniel Ríos",
    status: "Pending",
    assetId: "CMP-01",
    plant: PLANT,
    workOrder: "OT-ALM-P112",
    toolIds: ["tool-thermal"],
    eligibilityValidated: true,
  },
  {
    id: "s-transformer",
    protocolId: "p-electrical-inspection",
    date: today,
    hour: "08:00",
    tolerance: 20,
    operator: "Laura Vázquez",
    status: "Completed",
    assetId: "TRS-02",
    plant: PLANT,
    workOrder: "OT-ALM-2397",
  },
  {
    id: "s-furnace",
    protocolId: "p-furnace-thermal",
    date: today,
    hour: "08:45",
    tolerance: 20,
    operator: "Laura Vázquez",
    status: "Completed",
    assetId: "HOR-01",
    plant: PLANT,
    workOrder: "OT-ALM-2401",
  },
  {
    id: "s-crane",
    protocolId: "p-crane-safety",
    date: demoNow().subtract(1, "day").format("YYYY-MM-DD"),
    hour: "07:30",
    tolerance: 15,
    operator: "Mariana Torres",
    status: "Expired",
    assetId: "GRU-03",
    plant: PLANT,
    workOrder: "OT-ALM-2388",
  },
  {
    id: "s-mesh",
    protocolId: "p-mesh-preventive",
    date: tomorrow,
    hour: "13:00",
    tolerance: 30,
    operator: "Fernanda Ruiz",
    status: "Pending",
    assetId: "MAL-01",
    plant: PLANT,
    workOrder: "OT-ALM-P118",
    eligibilityValidated: true,
  },
];

export const seedReservations: ResourceReservation[] = [
  {
    id: "res-wire-asset",
    scheduleId: "s-wire-main",
    resourceType: "Asset",
    resourceId: "TRF-03",
    startAt: dayjs(`${today} 10:30`).toISOString(),
    endAt: dayjs(`${today} 12:00`).toISOString(),
    status: "Reserved",
  },
  {
    id: "res-wire-person",
    scheduleId: "s-wire-main",
    resourceType: "Person",
    resourceId: "per-eduardo",
    startAt: dayjs(`${today} 10:30`).toISOString(),
    endAt: dayjs(`${today} 12:00`).toISOString(),
    status: "Reserved",
  },
  ...["tool-loto", "tool-vibration", "tool-thermal"].map((resourceId) => ({
    id: `res-wire-${resourceId}`,
    scheduleId: "s-wire-main",
    resourceType: "Tool" as const,
    resourceId,
    startAt: dayjs(`${today} 10:30`).toISOString(),
    endAt: dayjs(`${today} 12:00`).toISOString(),
    status: "Reserved" as const,
  })),
];

export const seedExecutions: Execution[] = [
  {
    id: "e-transformer",
    scheduleId: "s-transformer",
    protocolId: "p-electrical-inspection",
    startAt: demoNow().hour(8).minute(2).toISOString(),
    endAt: demoNow().hour(8).minute(34).toISOString(),
    operator: "Laura Vázquez",
    status: "Validated",
    evidences: [],
    formAnswers: { thermal: "Sin desviaciones visibles en la inspección demostrativa." },
    approval: {
      supervisor: "Miguel Salas",
      decision: "Approved",
      comments: "Registro completo para demostración.",
      at: demoNow().hour(8).minute(42).toISOString(),
    },
    score: 96,
    revision: 1,
  },
  {
    id: "e-furnace",
    scheduleId: "s-furnace",
    protocolId: "p-furnace-thermal",
    startAt: demoNow().hour(8).minute(47).toISOString(),
    endAt: demoNow().hour(9).minute(22).toISOString(),
    operator: "Laura Vázquez",
    status: "PendingValidation",
    evidences: [],
    formAnswers: { condition: "Verificación demostrativa concluida; requiere liberación." },
    score: 91,
    revision: 1,
  },
];

export const seedIncidents: Incident[] = [
  {
    id: "inc-wire-condition",
    scheduleId: "s-wire-main",
    protocolId: "p-wire-condition",
    type: "Escalated",
    status: "Open",
    description:
      "Escenario demostrativo: se reportó ruido y vibración fuera de la condición habitual en Trefiladora 3.",
    createdAt: demoNow().subtract(35, "minute").toISOString(),
  },
  {
    id: "inc-crane-overdue",
    scheduleId: "s-crane",
    protocolId: "p-crane-safety",
    type: "NotExecuted",
    status: "Review",
    description: "Revisión visual demostrativa de Grúa 3 fuera de su ventana programada.",
    createdAt: demoNow().subtract(1, "day").toISOString(),
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "n-wire-alert",
    type: "Incident",
    channel: "System",
    actor: "Operación de planta",
    recipientRole: "admin",
    recipient: "Coordinación de mantenimiento",
    source: "OnDemand",
    event: "Condición reportada",
    message: "TRF-03 requiere diagnóstico por ruido y vibración reportada.",
    status: "Sent",
    createdAt: demoNow().subtract(35, "minute").toISOString(),
  },
  {
    id: "n-furnace-validation",
    type: "ValidationRequired",
    channel: "Push",
    actor: "Laura Vázquez",
    recipientRole: "supervisor",
    recipient: "Miguel Salas",
    source: "Automatic",
    event: "Validación requerida",
    message: "OT-ALM-2401 está lista para revisión.",
    status: "Sent",
    createdAt: demoNow().subtract(8, "minute").toISOString(),
  },
];

export const seedOperationalFlows: OperationalFlow[] = [
  {
    id: "flow-wire-release",
    name: "Atención y liberación de equipo",
    description: "Reporte, preparación, intervención, validación y liberación supervisada.",
    assetId: "TRF-03",
    status: "Ready",
    steps: [
      {
        id: "wire-report",
        name: "Registrar condición",
        protocolId: "p-wire-condition",
        mode: "Linear",
        status: "Completed",
      },
      {
        id: "wire-plan",
        name: "Preparar intervención",
        protocolId: "p-wire-condition",
        mode: "Linear",
        status: "Ready",
      },
      {
        id: "wire-execute",
        name: "Ejecutar protocolo",
        protocolId: "p-wire-condition",
        mode: "Linear",
        status: "Waiting",
      },
      {
        id: "wire-release",
        name: "Validar y liberar",
        protocolId: "p-wire-condition",
        mode: "Linear",
        status: "Waiting",
      },
    ],
  },
];

export const seedServiceRequests = [];
export const plants = [PLANT];
export const branches = [PLANT];
export const operators = seedPeople
  .filter((person) => person.role === "Technician")
  .map((person) => person.name);
export const supervisors = ["Miguel Salas"];
export const categories = ["Correctivo", "Preventivo", "Inspección", "Seguridad"];
