import dayjs from "dayjs";
import { demoNow } from "../../clock";
import type {
  Asset,
  Execution,
  Incident,
  InventoryItem,
  MaintenanceTool,
  Notification,
  OperationalFlow,
  Person,
  Protocol,
  ResourceReservation,
  Schedule,
  ServiceRequest,
  Skill,
} from "../../../ove/types";

const today = demoNow().format("YYYY-MM-DD");
const tomorrow = demoNow().add(1, "day").format("YYYY-MM-DD");

const atmPhotoManifest = [
  {
    id: "photo-before",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Vista general e identificación del ATM",
    phase: "Pre-intervention" as const,
    guidance: "Incluye el ATM completo y suficiente contexto del acceso y del sitio.",
    referenceData: "maintenance/atm-reference.svg",
    captureData: "maintenance/atm-field-before.jpg",
  },
  {
    id: "photo-during",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Intervención y trabajo ejecutado",
    phase: "Intervention" as const,
    guidance: "Muestra el componente intervenido, la herramienta y el trabajo en proceso.",
    referenceData: "maintenance/atm-reference.svg",
    captureData: "maintenance/atm-field-during.jpg",
  },
  {
    id: "photo-after",
    type: "Photo" as const,
    required: true,
    minCount: 1,
    label: "Resultado final y condición del sitio",
    phase: "Post-intervention" as const,
    guidance: "Muestra el ATM cerrado, el acabado final y el área liberada.",
    referenceData: "maintenance/atm-reference.svg",
    captureData: "maintenance/atm-field-after.jpg",
  },
];

export const seedAssets: Asset[] = [
  {
    id: "ATM-014",
    name: "ATM Comercio Norte 014",
    family: "Cajero automático",
    plant: "Región Norte",
    area: "Comercio · Acceso principal",
    criticality: "High",
    status: "Maintenance",
    availability: 96.4,
    health: 82,
    runtimeHours: 18420,
    lastService: demoNow().subtract(31, "day").toISOString(),
  },
  {
    id: "ATM-027",
    name: "ATM Sucursal Centro 027",
    family: "Cajero automático",
    plant: "Región Norte",
    area: "Sucursal bancaria · Vestíbulo",
    criticality: "Critical",
    status: "Available",
    availability: 99.1,
    health: 94,
    runtimeHours: 23110,
    lastService: demoNow().subtract(12, "day").toISOString(),
  },
  {
    id: "ATM-063",
    name: "ATM Torre Poniente 063",
    family: "Cajero automático",
    plant: "Región Poniente",
    area: "Torre residencial · Lobby",
    criticality: "Medium",
    status: "Risk",
    availability: 92.8,
    health: 71,
    runtimeHours: 12780,
    lastService: demoNow().subtract(46, "day").toISOString(),
  },
  {
    id: "ATM-091",
    name: "ATM Mall Oriente 091",
    family: "Cajero automático",
    plant: "Región Oriente",
    area: "Mall · Pasillo central",
    criticality: "High",
    status: "Available",
    availability: 97.6,
    health: 89,
    runtimeHours: 15390,
    lastService: demoNow().subtract(25, "day").toISOString(),
  },
];

export const seedSkills: Skill[] = [
  { id: "sk-atm-maint", name: "Mantenimiento de ATM", category: "Technical" },
  { id: "sk-atm-access", name: "Protocolo de acceso a sitio", category: "Safety" },
  { id: "sk-atm-elec", name: "Diagnóstico eléctrico básico", category: "Technical" },
  { id: "sk-atm-bank", name: "Identificación bancaria vigente", category: "Certification" },
];

export const seedPeople: Person[] = [
  {
    id: "per-luis",
    name: "Luis Campos",
    role: "Technician",
    plant: "Región Norte",
    shift: "Morning",
    skillIds: ["sk-atm-maint", "sk-atm-access", "sk-atm-elec", "sk-atm-bank"],
    certificationValidUntil: demoNow().add(9, "month").format("YYYY-MM-DD"),
    status: "Available",
  },
  {
    id: "per-andrea",
    name: "Andrea Morales",
    role: "Technician",
    plant: "Región Norte",
    shift: "Morning",
    skillIds: ["sk-atm-maint", "sk-atm-access", "sk-atm-bank"],
    certificationValidUntil: demoNow().add(6, "month").format("YYYY-MM-DD"),
    status: "Assigned",
  },
  {
    id: "per-daniel",
    name: "Daniel Soto",
    role: "Technician",
    plant: "Región Poniente",
    shift: "Afternoon",
    skillIds: ["sk-atm-maint", "sk-atm-access"],
    certificationValidUntil: demoNow().add(4, "month").format("YYYY-MM-DD"),
    status: "Available",
  },
  {
    id: "per-sofia",
    name: "Sofía Vega",
    role: "Supervisor",
    plant: "Región Norte",
    shift: "Morning",
    skillIds: ["sk-atm-maint", "sk-atm-access", "sk-atm-bank"],
    status: "Available",
  },
];

export const seedTools: MaintenanceTool[] = [
  {
    id: "tool-atm-kit",
    name: "Kit de servicio ATM",
    serial: "KIT-ATM-2408",
    plant: "Región Norte",
    location: "Unidad móvil N-04",
    status: "Available",
  },
  {
    id: "tool-meter",
    name: "Multímetro digital",
    serial: "MD-6614",
    plant: "Región Norte",
    location: "Unidad móvil N-04",
    status: "Available",
    calibrationValidUntil: demoNow().add(8, "month").format("YYYY-MM-DD"),
  },
  {
    id: "tool-access",
    name: "Kit de señalización y acceso",
    serial: "ACC-118",
    plant: "Región Norte",
    location: "Almacén regional",
    status: "Reserved",
  },
];

export const seedInventory: InventoryItem[] = [
  {
    id: "mat-paint",
    sku: "PNT-EXT-04",
    name: "Pintura para acabado exterior",
    unit: "L",
    plant: "Región Norte",
    warehouse: "Almacén regional N-01",
    onHand: 28,
    reserved: 4,
    quarantine: 0,
    reorderPoint: 8,
  },
  {
    id: "mat-clean-atm",
    sku: "CLN-ATM",
    name: "Consumibles de limpieza",
    unit: "kit",
    plant: "Región Norte",
    warehouse: "Almacén regional N-01",
    onHand: 42,
    reserved: 3,
    quarantine: 0,
    reorderPoint: 12,
  },
  {
    id: "mat-fastener",
    sku: "FST-ATM-06",
    name: "Juego de fijaciones para gabinete",
    unit: "jgo",
    plant: "Región Norte",
    warehouse: "Almacén regional N-01",
    onHand: 16,
    reserved: 1,
    quarantine: 0,
    reorderPoint: 5,
  },
];

export const seedProtocols: Protocol[] = [
  {
    id: "p-atm-corrective-commerce",
    name: "Correctivo ATM · Comercio",
    description:
      "Atención correctiva con identificación, evidencia ligada al sitio, registro de conceptos y validación de cierre.",
    category: "Correctivo",
    priority: "Critical",
    status: "Active",
    branches: ["Región Norte"],
    recurrence: "Once",
    schedule: [{ hour: "14:00", tolerance: 30 }],
    evidenceConfig: [
      { id: "location", type: "GPS", required: true, radius: 80, label: "Ubicación del servicio" },
      {
        id: "arrival-time",
        type: "Timestamp",
        required: true,
        label: "Fecha y hora de llegada",
      },
      ...atmPhotoManifest,
      { id: "signature", type: "Signature", required: true, label: "Firma del técnico" },
    ],
    formConfig: [
      { id: "diagnosis", type: "textarea", label: "Diagnóstico inicial", required: true },
      {
        id: "operation",
        type: "select",
        label: "Prueba de operación",
        required: true,
        options: ["Operación correcta", "Operación con observaciones", "No disponible"],
      },
      { id: "clean", type: "yesno", label: "Limpieza final realizada", required: true },
      { id: "notes", type: "comment", label: "Observaciones del técnico" },
    ],
    supervisors: ["Sofía Vega"],
    operators: ["Luis Campos", "Andrea Morales"],
    channels: ["System", "WhatsApp", "Email"],
    preAlertMinutes: 60,
    requiresValidation: true,
    activationMode: "OnDemand",
    triggerEvent: "Solicitud correctiva aceptada",
    assetIds: ["ATM-014"],
    materials: ["Pintura exterior · hasta 4 L", "Consumibles de limpieza · 1 kit"],
    safetyInstructions: [
      "Validar identidad y autorización de acceso",
      "Delimitar el área antes de intervenir",
      "No capturar usuarios ni información bancaria en la evidencia",
    ],
    estimatedMinutes: 120,
    allowRescheduling: true,
    requiredSkillIds: ["sk-atm-maint", "sk-atm-access", "sk-atm-bank"],
    requiredToolIds: ["tool-atm-kit", "tool-meter"],
    materialRequirements: [
      { inventoryItemId: "mat-paint", mode: "Range", min: 2, max: 4 },
      { inventoryItemId: "mat-clean-atm", mode: "Exact", quantity: 1 },
    ],
    workConceptTemplates: [
      { code: "CF-014", description: "Pintura exterior", unit: "M²", quantity: 12 },
      { code: "PA-006", description: "Ajuste de puerta de acceso", unit: "SERV", quantity: 1 },
    ],
  },
  {
    id: "p-atm-preventive-site",
    name: "Preventivo mensual ATM · SITE",
    description:
      "Rutina mensual programada para limpieza, inspección física, fijaciones y condición general del ATM.",
    category: "Preventivo",
    priority: "High",
    status: "Active",
    branches: ["Región Norte"],
    recurrence: "Monthly",
    schedule: [{ hour: "09:00", tolerance: 30 }],
    evidenceConfig: [
      { id: "location", type: "GPS", required: true, radius: 80, label: "Ubicación del servicio" },
      ...atmPhotoManifest,
      { id: "signature", type: "Signature", required: true, label: "Firma del técnico" },
    ],
    formConfig: [
      { id: "cleaning", type: "yesno", label: "Limpieza integral realizada", required: true },
      {
        id: "cabinet",
        type: "select",
        label: "Condición del gabinete",
        required: true,
        options: ["Correcta", "Con desgaste", "Requiere correctivo"],
      },
      { id: "notes", type: "comment", label: "Hallazgos" },
    ],
    supervisors: ["Sofía Vega"],
    operators: ["Luis Campos", "Andrea Morales"],
    channels: ["System", "Email"],
    preAlertMinutes: 120,
    requiresValidation: true,
    activationMode: "Recurring",
    triggerEvent: "Plan preventivo mensual",
    assetIds: ["ATM-027", "ATM-091"],
    materials: ["Consumibles de limpieza · 1 kit"],
    safetyInstructions: ["Confirmar ventana con la sucursal", "Portar identificación vigente"],
    estimatedMinutes: 60,
    allowRescheduling: true,
    requiredSkillIds: ["sk-atm-maint", "sk-atm-access", "sk-atm-bank"],
    requiredToolIds: ["tool-atm-kit", "tool-access"],
    materialRequirements: [{ inventoryItemId: "mat-clean-atm", mode: "Exact", quantity: 1 }],
    workConceptTemplates: [
      {
        code: "PM-001",
        description: "Mantenimiento preventivo mensual",
        unit: "SERV",
        quantity: 1,
      },
    ],
  },
];

const correctiveCommerce = seedProtocols[0];
seedProtocols.push(
  {
    ...correctiveCommerce,
    id: "p-atm-corrective-bank",
    name: "Correctivo ATM · Banco",
    description: "Variante visible para acceso dentro de sucursal bancaria.",
    assetIds: ["ATM-027"],
    safetyInstructions: [
      "Confirmar ventana con la sucursal",
      "Validar identificación bancaria vigente",
      "Mantener acompañamiento cuando sea requerido",
    ],
  },
  {
    ...correctiveCommerce,
    id: "p-atm-corrective-residential",
    name: "Correctivo ATM · Torre residencial",
    description: "Variante visible para acceso controlado en torre residencial.",
    assetIds: ["ATM-063"],
    safetyInstructions: [
      "Confirmar autorización con recepción",
      "Registrar acceso y salida",
      "Respetar la ventana y áreas comunes",
    ],
  },
  {
    ...correctiveCommerce,
    id: "p-atm-corrective-mall",
    name: "Correctivo ATM · Mall",
    description: "Variante visible para intervención en horario y acceso de centro comercial.",
    assetIds: ["ATM-091"],
    safetyInstructions: [
      "Confirmar horario permitido por administración",
      "Delimitar el área de tránsito",
      "Coordinar acceso de herramientas y materiales",
    ],
  },
);

export const seedServiceRequests: ServiceRequest[] = [
  {
    id: "req-atm-2401",
    externalReference: "SO-ATM-2401",
    title: "Mantenimiento de acabado exterior y puerta de acceso",
    description:
      "Se reporta deterioro del acabado exterior y ajuste requerido en la puerta de acceso.",
    source: "Banco Delta · canal de servicios simulado",
    assetId: "ATM-014",
    siteLabel: "Comercio Norte 014",
    region: "Región Norte",
    receivedAt: demoNow().subtract(20, "hour").toISOString(),
    acceptanceDueAt: demoNow().add(4, "hour").toISOString(),
    acceptancePolicy: { durationHours: 24, expiresTo: "Expired" },
    requiresAcceptance: true,
    status: "Received",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Comercio",
    },
    accessRequirements: [
      {
        id: "appointment",
        label: "Cita previa confirmada",
        required: true,
        completed: true,
        detail: "14 ago · 10:00",
      },
      {
        id: "identification",
        label: "Identificación del técnico",
        required: true,
        completed: false,
        detail: "Se adjunta al asignar técnico",
      },
      {
        id: "escort",
        label: "Acompañamiento",
        required: false,
        completed: true,
        detail: "No requerido",
      },
      {
        id: "site-reference",
        label: "Referencia del sitio",
        required: true,
        completed: true,
        detail: "Acceso principal del comercio",
      },
    ],
    protocolId: "p-atm-corrective-commerce",
  },
  {
    id: "req-atm-2389",
    externalReference: "SO-ATM-2389",
    title: "Falla intermitente de lector",
    description: "Solicitud correctiva no aceptada dentro de la ventana configurada.",
    source: "Banco Delta · canal de servicios simulado",
    assetId: "ATM-063",
    siteLabel: "Torre Poniente 063",
    region: "Región Poniente",
    receivedAt: demoNow().subtract(26, "hour").toISOString(),
    acceptanceDueAt: demoNow().subtract(2, "hour").toISOString(),
    acceptancePolicy: { durationHours: 24, expiresTo: "Expired" },
    requiresAcceptance: true,
    status: "Expired",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Torre residencial",
    },
    accessRequirements: [],
    protocolId: "p-atm-corrective-residential",
  },
  {
    id: "req-atm-p082",
    externalReference: "PLAN-ATM-082",
    title: "Preventivo mensual programado",
    description: "Servicio incluido en el plan preventivo recibido con un mes de anticipación.",
    source: "Plan mensual simulado",
    assetId: "ATM-027",
    siteLabel: "Sucursal Centro 027",
    region: "Región Norte",
    receivedAt: demoNow().subtract(12, "day").toISOString(),
    requiresAcceptance: false,
    status: "Planned",
    classification: {
      serviceType: "Preventivo",
      installationClass: "SITE",
      accessContext: "Banco",
    },
    accessRequirements: [
      {
        id: "branch-window",
        label: "Ventana con sucursal",
        required: true,
        completed: true,
        detail: "Programa mensual confirmado",
      },
    ],
    protocolId: "p-atm-preventive-site",
    scheduleId: "s-atm-preventive",
  },
  {
    id: "req-atm-2374",
    externalReference: "SO-ATM-2374",
    title: "Ajuste físico de gabinete",
    description: "Correctivo aceptado y cerrado en un sitio con protocolo de acceso a mall.",
    source: "Banco Delta · canal de servicios simulado",
    assetId: "ATM-091",
    siteLabel: "Mall Oriente 091",
    region: "Región Oriente",
    receivedAt: demoNow().subtract(2, "day").toISOString(),
    acceptanceDueAt: demoNow().subtract(1, "day").toISOString(),
    acceptancePolicy: { durationHours: 24, expiresTo: "Expired" },
    requiresAcceptance: true,
    status: "Planned",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Mall",
    },
    accessRequirements: [],
    protocolId: "p-atm-corrective-mall",
    acceptedAt: demoNow().subtract(38, "hour").toISOString(),
    acceptedBy: "Marina Ortega",
    scheduleId: "s-atm-closed",
  },
];

export const seedSchedules: Schedule[] = [
  {
    id: "s-atm-demo-commerce",
    protocolId: "p-atm-corrective-commerce",
    date: today,
    hour: "10:30",
    tolerance: 30,
    operator: "Luis Campos",
    status: "Pending",
    assetId: "ATM-014",
    plant: "Región Norte",
    workOrder: "OT-ATM-2412",
    serviceReference: "SO-ATM-2412",
    siteLabel: "Comercio Norte 014",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Comercio",
    },
    accessRequirements: [
      {
        id: "site-contact",
        label: "Contacto del sitio confirmado",
        required: true,
        completed: true,
        detail: "Acceso principal · 10:20",
      },
    ],
    toolIds: ["tool-atm-kit", "tool-meter"],
    materialAllocations: [
      {
        inventoryItemId: "mat-paint",
        mode: "Range",
        min: 2,
        max: 4,
        reservedQuantity: 3,
      },
      {
        inventoryItemId: "mat-clean-atm",
        mode: "Exact",
        quantity: 1,
        reservedQuantity: 1,
      },
    ],
    eligibilityValidated: true,
    notes: "Correctivo aceptado previamente por coordinación.",
  },
  {
    id: "s-atm-demo-bank",
    protocolId: "p-atm-corrective-bank",
    date: today,
    hour: "13:00",
    tolerance: 30,
    operator: "Luis Campos",
    status: "Pending",
    assetId: "ATM-027",
    plant: "Región Norte",
    workOrder: "OT-ATM-2416",
    serviceReference: "SO-ATM-2416",
    siteLabel: "Sucursal Centro 027",
    classification: {
      serviceType: "Correctivo",
      installationClass: "SITE",
      accessContext: "Banco",
    },
    accessRequirements: [
      {
        id: "branch-window",
        label: "Ventana con sucursal confirmada",
        required: true,
        completed: true,
        detail: "Acceso con acompañamiento · 12:50",
      },
    ],
    toolIds: ["tool-atm-kit", "tool-access"],
    materialAllocations: [
      {
        inventoryItemId: "mat-fastener",
        mode: "Exact",
        quantity: 1,
        reservedQuantity: 1,
      },
    ],
    eligibilityValidated: true,
    notes: "Correctivo aceptado previamente por coordinación.",
  },
  {
    id: "s-atm-demo-residential",
    protocolId: "p-atm-corrective-residential",
    date: tomorrow,
    hour: "09:00",
    tolerance: 30,
    operator: "Luis Campos",
    status: "Pending",
    assetId: "ATM-063",
    plant: "Región Poniente",
    workOrder: "OT-ATM-2420",
    serviceReference: "SO-ATM-2420",
    siteLabel: "Torre Poniente 063",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Torre residencial",
    },
    accessRequirements: [
      {
        id: "reception-authorization",
        label: "Autorización de recepción",
        required: true,
        completed: true,
        detail: "Registro de acceso requerido",
      },
    ],
    toolIds: ["tool-atm-kit", "tool-meter"],
    materialAllocations: [
      {
        inventoryItemId: "mat-clean-atm",
        mode: "Exact",
        quantity: 1,
        reservedQuantity: 1,
      },
    ],
    eligibilityValidated: true,
    notes: "Correctivo aceptado previamente por coordinación.",
  },
  {
    id: "s-atm-preventive",
    protocolId: "p-atm-preventive-site",
    date: today,
    hour: "09:00",
    tolerance: 30,
    operator: "Andrea Morales",
    status: "Pending",
    assetId: "ATM-027",
    plant: "Región Norte",
    workOrder: "OT-ATM-P082",
    serviceReference: "PLAN-ATM-082",
    siteLabel: "Sucursal Centro 027",
    serviceRequestId: "req-atm-p082",
    classification: {
      serviceType: "Preventivo",
      installationClass: "SITE",
      accessContext: "Banco",
    },
    toolIds: ["tool-atm-kit", "tool-access"],
    materialAllocations: [
      {
        inventoryItemId: "mat-clean-atm",
        mode: "Exact",
        quantity: 1,
        reservedQuantity: 1,
      },
    ],
    eligibilityValidated: true,
  },
  {
    id: "s-atm-closed",
    protocolId: "p-atm-corrective-mall",
    date: today,
    hour: "08:00",
    tolerance: 30,
    operator: "Luis Campos",
    status: "Completed",
    assetId: "ATM-091",
    plant: "Región Oriente",
    workOrder: "OT-ATM-2374",
    serviceRequestId: "req-atm-2374",
    serviceReference: "SO-ATM-2374",
    siteLabel: "Mall Oriente 091",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Mall",
    },
  },
  {
    id: "s-atm-review",
    protocolId: "p-atm-corrective-residential",
    date: today,
    hour: "07:30",
    tolerance: 30,
    operator: "Andrea Morales",
    status: "Completed",
    assetId: "ATM-063",
    plant: "Región Poniente",
    workOrder: "OT-ATM-2392",
    serviceReference: "SO-ATM-2392",
    siteLabel: "Torre Poniente 063",
    classification: {
      serviceType: "Correctivo",
      installationClass: "REMOTO",
      accessContext: "Torre residencial",
    },
  },
];

export const seedReservations: ResourceReservation[] = [
  {
    id: "res-atm-p082-person",
    scheduleId: "s-atm-preventive",
    resourceType: "Person",
    resourceId: "per-andrea",
    startAt: dayjs(`${today} 09:00`).toISOString(),
    endAt: dayjs(`${today} 10:00`).toISOString(),
    status: "Reserved",
  },
  {
    id: "res-atm-p082-tool",
    scheduleId: "s-atm-preventive",
    resourceType: "Tool",
    resourceId: "tool-access",
    startAt: dayjs(`${today} 09:00`).toISOString(),
    endAt: dayjs(`${today} 10:00`).toISOString(),
    status: "Reserved",
  },
];

const evidence = (executionId: string) => {
  const gps = { lat: 25.6866, lng: -100.3161 };
  const timestamp = demoNow().toISOString();
  return [
    {
      id: `${executionId}-gps`,
      executionId,
      type: "GPS" as const,
      data: `${gps.lat},${gps.lng}`,
      gps,
      label: "Ubicación del servicio",
      timestamp,
      status: "Valid" as const,
    },
    ...atmPhotoManifest.map((item) => ({
      id: `${executionId}-${item.id}`,
      executionId,
      type: "Photo" as const,
      data: item.captureData,
      referenceData: item.referenceData,
      gps,
      label: item.label,
      phase: item.phase,
      timestamp,
      status: "Valid" as const,
      aiScore: 92,
      humanScore: 5,
      aiFindings: [
        "Activo y contexto visibles",
        "Toma asociada al manifiesto",
        "Sello de ubicación completo",
      ],
      operatorComment: "Evidencia simulada asociada al sitio y a la orden asignada.",
    })),
    {
      id: `${executionId}-signature`,
      executionId,
      type: "Signature" as const,
      data: "signature://operator",
      label: "Firma del técnico",
      timestamp,
      status: "Valid" as const,
    },
  ];
};

export const seedExecutions: Execution[] = [
  {
    id: "e-atm-closed",
    scheduleId: "s-atm-closed",
    protocolId: "p-atm-corrective-mall",
    startAt: demoNow().hour(8).minute(2).toISOString(),
    endAt: demoNow().hour(9).minute(50).toISOString(),
    operator: "Luis Campos",
    status: "Validated",
    evidences: evidence("e-atm-closed"),
    formAnswers: {
      diagnosis: "Desgaste exterior y holgura menor en acceso.",
      operation: "Operación correcta",
      clean: true,
    },
    workConcepts: [
      { code: "CF-014", description: "Pintura exterior", unit: "M²", quantity: 12 },
      { code: "PA-006", description: "Ajuste de puerta de acceso", unit: "SERV", quantity: 1 },
    ],
    approval: {
      supervisor: "Sofía Vega",
      decision: "Approved",
      comments: "Evidencia y cierre completos.",
      at: demoNow().toISOString(),
    },
    score: 96,
    revision: 2,
  },
  {
    id: "e-atm-review",
    scheduleId: "s-atm-review",
    protocolId: "p-atm-corrective-residential",
    startAt: demoNow().hour(7).minute(32).toISOString(),
    endAt: demoNow().hour(8).minute(48).toISOString(),
    operator: "Andrea Morales",
    status: "PendingValidation",
    evidences: evidence("e-atm-review"),
    formAnswers: {
      diagnosis: "Ajuste físico y limpieza del frente.",
      operation: "Operación con observaciones",
      clean: true,
    },
    workConcepts: [
      { code: "PA-006", description: "Ajuste de puerta de acceso", unit: "SERV", quantity: 1 },
    ],
    score: 84,
    revision: 1,
  },
];

export const seedIncidents: Incident[] = [
  {
    id: "inc-atm-2392",
    executionId: "e-atm-review",
    scheduleId: "s-atm-review",
    protocolId: "p-atm-corrective-residential",
    type: "Escalated",
    status: "Review",
    description: "La evidencia final requiere revisión de encuadre antes del cierre.",
    createdAt: demoNow().toISOString(),
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "n-atm-intake",
    type: "PreviousAlert",
    channel: "System",
    actor: "Service Intake",
    recipientRole: "admin",
    recipient: "Marina Ortega",
    source: "Automatic",
    event: "Correctivo recibido",
    message: "SO-ATM-2401 requiere aceptación antes de vencer su ventana.",
    status: "Sent",
    createdAt: demoNow().subtract(20, "hour").toISOString(),
  },
  {
    id: "n-atm-validation",
    type: "ValidationRequired",
    channel: "Push",
    actor: "Andrea Morales",
    recipientRole: "supervisor",
    recipient: "Sofía Vega",
    source: "Automatic",
    event: "Validación requerida",
    message: "OT-ATM-2392 está lista para revisión.",
    status: "Sent",
    createdAt: demoNow().subtract(40, "minute").toISOString(),
  },
];

export const seedOperationalFlows: OperationalFlow[] = [
  {
    id: "flow-atm-corrective",
    name: "Atención correctiva ATM",
    description: "Aceptación, programación, ejecución, validación y reporte.",
    assetId: "ATM-014",
    status: "Ready",
    steps: [
      {
        id: "flow-atm-accept",
        name: "Aceptar y clasificar",
        protocolId: "p-atm-corrective-commerce",
        mode: "Linear",
        status: "Ready",
      },
      {
        id: "flow-atm-execute",
        name: "Ejecutar servicio",
        protocolId: "p-atm-corrective-commerce",
        mode: "Linear",
        status: "Waiting",
      },
      {
        id: "flow-atm-validate",
        name: "Validar y reportar",
        protocolId: "p-atm-corrective-commerce",
        mode: "Linear",
        status: "Waiting",
      },
    ],
  },
];

export const plants = ["Región Norte", "Región Poniente", "Región Oriente"];
export const branches = ["Región Norte", "Región Poniente", "Región Oriente"];
export const operators = ["Luis Campos", "Andrea Morales", "Daniel Soto"];
export const supervisors = ["Sofía Vega"];
export const categories = ["Correctivo", "Preventivo"];
